jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw
- sudo apt-get update
- sudo apt-get install rubygems
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: 61hvsaaRqhtB9bJqDFAGBGoJeFANKqw5fF0akEfeuaj4w5X0kg+GWEPipWHpyeuGNairNVMTSXd8bMNEjk0FaKQLZ62LT4eg//c/lHXHfeR5dteJOaU16GvZ6pqoUuVDT7BiAuOlUXXdd++FgKYpWO2fanDEEPC8MyjdLMDMAAV8LvruDIjUnTuOXJaoV+lO60+7uicW4PQpB9KVg+tOQoeSxtbzvpJ50kwlEXZyf4loF6n4tBz5xXMDkoaHvlyrKH2D9Xp/5JgSNcxc3vznoQaaRWSjOND/DN5qa5OLALJy4gbf1EU+6iwvCmTbWecXYIDRwhb4D9CtY9PPQTS/CmrPUiWc4D1v5H31JNuCr4z2AnX9D1IaOg2/snChYi9qt6z5FM+fqyQx2zDR8gkJrmBFgeS34FgmQ+TH0By65K06BLiNMb1/QcPI+RixPyvsTtUJsqaa/E4phQDLc85TS1hIuZ+NLj3Lr9ws57xth6JLfPfyzUUZJlJ7GX0CtpFq0y1WzmB3b0qUbRAUkJ+Cv4d2p5lLy0cIKGz39AU0z/4YzWb7NtQNVfap76qsDp1reGLMg+6HrY6UK4OXQRuuINIy84TGuN50iB/Gug9jkKKPvnrDKC0dS3IXfIgtjpXvWs2LUD7nyduORZZSSTwBNHwYCmeikhEBkg3RyZ0omVQ=
