jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: kGI7KGs76e2M+GNalDsbjhW0/Dx3kA+3V9XOEjF4XolcP0oOwAN/Yw1vGcOBlEEJ8+Lt04H9Drf1/9aoR21RqPcgMZcqEsbm3XqXXbZ3+lZkXytXlvfrlhSp3xFKJu1QYYNgqPaGFMc/6MdQARzHe7JciME8UEgxa82Z6UHtOzHmLnvzNhCjfe71rHQJe5KbpViG7J7Sk4vVydwtMK+NVb5tTp7ZsqaVngJDPjNKrDeGiY2JYSeDAOnTJNLmnHXHi65WPyjluZVVPT1/oYVl0iF1RYyXIT9PBE8s1gBUObsBWiXyNytqTJGET9ZFjahM8hrwW8B8pBLArbtUZvMH/LUDPjHTVGt35ZK5+QzGgXz+oJuamawcsiGZAbXvmxX2zkl2PL94a4TZ8r2WQO8Y5DPVxjHeGKOQTU6nL45i0vghxjcL08YjL9+fntn1cTkcCwOFM4e1Ksity2sriBb+HDHZPYwmcHf+GgwhRqxF12Euy7eyQcr/DErKRbmE2m91DGUrYXohqChLPf8v9F6mLbLPEEiEyTwZquShQxh98eNX+XX0aaJhI6EtkD+ylA3euFRRdsXBss25ErmktZ9a6gGoo2Hda+I0skCkyaplgTrq4il+X17uiRTdbIh1jCawlbB6aoNH55e+bzdB7RkoN6/6damYlC53kMhTo6uQFAg=
  app: interbikeshop