jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: AmZkZ/LyEpLrSXP8lND+SAb2aWmF7/1rlcF7KL42JB+6MnUEFHaIPL5KkgS0K2i2Pa6GosgbvXS6qFzcqvUEgtxZMLZIdaTUwOQcnWGMZZKmvnuiUPNr+XnsNM1tla+Zuok142emu2oO1N0T/YADQWKG1Fuob6W5LWgPBThZEG1T3Wp5BCmzaCaPOC9AuxK45nr8TgxQzjJq1M+JWGITWJZzPSx/r3N+9G7wRui0EXz/Cm+w1VCIcBzOp7zK2yhqsDs+PculBdM/9v2LYV4tBNzazCA3yJgAhCj7OBkkfW2pX7r5WnEYiPQzY/FdUAHczYkpMlyzpwQZO6/j+HrNEgoElBer/8h+TFnj1Tnl6QnEQDSJgxZeUKxB/lpD+0xF5hPdxBc5LVXxrrXtP/L2v3Tme+CyGli7j/+wuT3HRLDa6aOSRNz1qQ7a0X+v6b5CG4KOw0C+FMIreto5AS9c+jLU9qv6AUSJQ9t8k4zmgg4eA1D+EXRI2539wbv8Xe0h01F151p9aGR85Vl6o2Scvem0m1sxX0lZeE64ze3Gk+xT9S+YpzNkUFFMSK9Bv204GVq32VrndqrDGYSOsx9eElrIWRbFIKhlbotGES35m1PVYfnWKoR5n7R7ca1WyEowr0HONAkh1D9HEpv9+156KDl46hmfdiZ/tfeb+Sp8sIQ=
    app: interbikeshop