jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
- chmod +x mvnw
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: vrbIWKni+c3HDcqpauy5ksA/2GadTBFhcMiHOoXYVcbd62Z4MC14jlwjhTe3Mj1cHA4HU3vFbw/JFu0zWg7SvxvTBcG/uvtNWSHe1feJCdWoheDuRdjDuQZW/VaUzWam7zF3lYcVEN3dR+HMU3qc/jb6+3d59Ju6F2ksDwIwPb1/GDWltu5114GM/5oENhAd127OE8+hp1aqxvtprJTa/Cf+x3YqgFTJps7nTF9KibBAu8bz2YU6FnHvsqtqHa8ulQ95x/ELNFcioOnJP5SlUkb32Js3JCE1VG4/1Dmx85pXwSnWZ7KXWZ7a2omVyvKE5AsITXeaxGL92BHJBJCitP6uTfuhN4gX7bGPSs2B/eMEEoXlii8KrBjGyldC+lfC6o2tyeohf0e86Cn7T8LSRF74nP2CzsVi9NXqjIx9ShbhLPWF4Z8ZxFX+PI/wrDaGc1XCEzxuoDUe4dWzjpcMha15+t+DNPxdiD/hfBXKezYO+C+LH7DdwKWbgEkuK3wX8M+8RA87kUhiPkbRP3WLh/ALRrJO6oTeZucVS3VyzgFDcPqRh/h0HQxGnzPl/VjNwhWIe45enzYgJUKNgX5S8WdcMVFGl4qgcsqTJFbFtIyFtjHyUcqlvegyIC4xT07s60i4rCewD70hR8qla/w0jV9pXAkKJLupVcAA1DUp+Ak=
