    jdk:
      - openjdk8
    install:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    before_install:
      - chmod +x mvnw
    script:
      - mvn test
    deploy:
          provider: heroku
          api_key:
                secure: "5ade8704-ce2c-4ce7-bdf3-07cf6d460fd6"